### ISSUE TITLE
global() Richness_x bug

### ISSUE THREAD

**Issue by xvazquezc** [microbiome/microbiome#80]
Hi there,

I started to use this package a couple of weeks ago and I realised that the output from `global()` for each of the richness measures is exactly the same. All `richness_0`, `richness_20`, `richness_50` and `richness_80` are identical to `observed`.

I'm using version 1.0.2

Cheers,
Xabi

**Comment by microsud** [comment]
Hi Xabi,
I think this bug is fixed in version 1.2.1 available via BioC.

Do you find it also with datasets from package e.g atlas1006?

Let us know and we will try to fix if the issues pops up again.

Cheers,
Sudarshan

**Comment by xvazquezc** [comment]
I had to update R in order to get the newest BioConductor to install 1.2.1, but still doesn't seem to work

That's really weird, with atlas1006, the calculated values look fine, but not in my dataset...

**Comment by antagomir** [comment]
The method uses data quantiles as follows: quantile(as.vector(otu), c(0, 0.2, 0.5, 0.8))

If your data has very many 0's (>80%) for instance, it could be that all quantiles are the same (0) and subsequently richness estimates would be identical for these thresholds. Could this be an explanation.

**Comment by xvazquezc** [comment]
That's exactly the case, very few OTUs per sample but the whole dataset is quite diverse.

But shouldn't the function ignore the zeroes? After all, the richness is based on the species that are present in the sample, not about what *can* be present.

e.g. doing this for a single sample, returns the proper values:
```r
otu = abundances(physeq, transform = "compositional" )
this = sort(as.vector(as.data.frame(otu)$SRR6449887), decreasing = T)  #SRR6449887 is one of the samples
this[which(this==0)] = NA
quantile(this, probs = c(0, 0.2, 0.5, 0.8), na.rm = T)
```

I don't have the expertise in R programming to implement it in a function though...

**Comment by antagomir** [comment]
If you need that, you can either set a non-zero threshold manually (detection argument in the function call).

The function is indeed ignoring zeroes. The richness estimates is the number of OTUs that exceed a given abundance threshold. In the above case, the same threshold (0) each obtained with all quantiles across the complete data set. Of course it would be possible to calculate the quantiles separately for each sample but using a different detection threshold per sample is problematic and it is not intuitively clear to me how to interpret such richness values between samples, although ability to compare is typically to goal in this kind of analyses. All standard methods for richness estimation use the same threshold across all samples.
